### ISSUE TITLE
Better basis vectors for dhdm files

### ISSUE THREAD

**Issue by Xin-888** [edolstra/dhdm#5]
Hello edolstra. A while ago someone pointed out that morphs don't exactly deform the mesh like in daz, so I looked closer at what matrix daz uses when transforming the dhdm coordinates to object space coordinates (see issue [at the bottom here](https://bitbucket.org/Diffeomorphic/import_daz/issues/357/blender-addon-to-generate-rigged-hd-meshes)).

I ended up concluding that the algorithm implemented [here](https://gitlab.com/x190/daz-hd-morphs/-/blob/main/dll_source/subdivide.cc) works better (can't do extensive testing because my computer is quite old and tends to crash with high subdivision levels). It also handles triangles, not just quads. Basically, for each base face, there is a matrix (set of basis vectors) constructed for each edge of that face. Then, depending on which subdivided face you are considering, you pick one of those matrices (e.g. if you are at subdivision level 2 of a certain base face, the first 4 subdivided faces of that base face use the matrix corresponding to one edge of the base face; the next 4 the matrix of the next edge; and so on).

Specifically, look at the function "getDhdmMats()" in subdivide.cc. Then look at how it's used later by searching "submat_idx" in the same file.

**Comment by edolstra** [comment]
@Xin-888 Thanks! It does look better though I haven't tested it a lot yet.
